// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"database/sql"
)

type Group struct {
	ID        int32
	Groupname string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Permission struct {
	ID        int32
	Title     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID             int32
	Username       string
	Email          string
	HashedPassword string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}
