services:
  # auth-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db
  #   ports:
  #     - 8080:8080
  
  db:
    image: postgres:latest
    container_name: auth-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-service-db
      DB_PORT: 5432
    ports:
      - "5432:5432"

  