name: CI/CD Pipeline for Go Application Deployment

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the main branch

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: SSH into EC2 to pull the repository and deploy
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Install nessesccery tools
            if [ -x "$(command -v yum)" ]; then
            sudo yum update -y
            sudo yum install -y git docker
            elif [ -x "$(command -v apt-get)" ]; then
              sudo apt-get update -y
              sudo apt-get install -y git docker.io
            fi
            # Start the Docker service
            sudo systemctl start docker
            sudo systemctl enable docker
      
            # Navigate to the home directory
            cd ~

            # Clone or pull the latest code from the repository
            if [ -d "app" ]; then
              cd app
              git reset --hard
              git pull https://raam-techie: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@github.com/raam-techie/flipopay-auth-server.git
            else
              git clone https://raam-techie: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@github.com/raam-techie/flipopay-auth-server.git
              cd app
            fi

            # Stop and remove the old Docker container if it exists
            docker stop myapp || true
            docker rm myapp || true

            # Build and run the new Docker container
            docker build -t myapp:latest .
            docker run -d --name myapp -p 8080:8080 myapp:latest
