name: CI/CD Pipeline for Go Application Deployment

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the main branch

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-24.04  # Use Ubuntu 24.04 for the GitHub runner

    steps:
      # Step 1: Deploy the application on EC2
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Install necessary dependencies on the EC2 instance
            if [ -x "$(command -v yum)" ]; then
              sudo yum update -y
              sudo yum install -y git docker
            elif [ -x "$(command -v apt-get)" ]; then
              sudo apt-get update -y
              sudo apt-get install -y git docker.io
            fi

            # Start Docker service
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker $USER

            # Clone or pull the latest code from the repository
            cd ~
            if [ -d "flipopay-auth-service" ]; then
              cd flipopay-auth-service
              git checkout main
              git fetch origin main
              git reset --hard origin/main
              git pull origin main
            else
              git clone https://${{ secrets.PAT_TOKEN }}@github.com/flipopay-technologies/flipopay-auth-service.git
              cd flipopay-auth-service
              git checkout main
            fi

            # Stop and remove the old Docker container if it exists
            sudo docker stop myapp || true
            sudo docker rm myapp || true

            # Build and run the Docker container
            sudo docker build -t myapp:latest -f deployment/Dockerfile .
            sudo docker run -d --name myapp -p 8080:8080 myapp:latest
